name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install SonarScanner
        run: |
          wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/bin/sonar-scanner

  sonarqube:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SonarQube Scanner
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: setup

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 80:80
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose up -d

  joomla:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP and Apache2
        run: |
          sudo apt-get update
          sudo apt-get install -y php libapache2-mod-php php-mysql
          sudo systemctl start apache2

      - name: Set up Database Server
        run: |
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root_password';"
          sudo mysql -e "CREATE USER 'joomla'@'localhost' IDENTIFIED BY 'joomla_password';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'joomla'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo mysql -e "CREATE DATABASE joomla;"

      - name: Run Joomla Tests
        run: |
          php -v
          apache2 -v
          mysql --version